Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - bin/run

Style/ParallelAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Style/Lambda:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

AllCops:
  Exclude:
    - './play_receiver.rb'
    - './play_generator.rb'
