version: '3.7'
services:
  base: &base
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '2.7.1'
        BUNDLER_VERSION: '2.1.4'
    image: krouter-dev:1.0.0
    depends_on:
      - kafka
      - redis

  creator:
    <<: *base
    command: rescue example/creator.rb

  worker:
    <<: *base
    command: ruby example/worker.rb

  receiver:
    <<: *base
    command: ruby example/receiver.rb

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181'
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - '9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  